### ISSUE TITLE
Affinity library warning on WI]ndows

### ISSUE THREAD

**Issue by keiran-lawrey** [OpenHFT/Chronicle-Queue-Demo#16]

**Comment by keiran-lawrey** [comment]
```
[main/disk~space~checker] WARN net.openhft.affinity.Affinity - Windows JNA-based affinity not usable because it failed to load! Reason: java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
	at net.openhft.affinity.impl.WindowsJNAAffinity$CLibrary.<clinit>(WindowsJNAAffinity.java:157)
	at net.openhft.affinity.impl.WindowsJNAAffinity.getAffinity0(WindowsJNAAffinity.java:100)
	at net.openhft.affinity.impl.WindowsJNAAffinity.getAffinity(WindowsJNAAffinity.java:64)
	at net.openhft.affinity.impl.WindowsJNAAffinity.<clinit>(WindowsJNAAffinity.java:49)
	at net.openhft.affinity.Affinity.isWindowsJNAAffinityUsable(Affinity.java:87)
	at net.openhft.affinity.Affinity.<clinit>(Affinity.java:45)
	at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:150)

[main/disk~space~checker] INFO net.openhft.affinity.Affinity - Using dummy affinity control implementation
```

BTW disk space checker doesn't need affinity so this initialization should be lazy
